<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Core\ABP.Core.Application\ABP.Core.Application.csproj" />
    <ProjectReference Include="..\..\Core\ABP.Core.Domain\ABP.Core.Domain.csproj" />
    <ProjectReference Include="..\ABP.Infraestructure.Shared\ABP.Infraestructure.Shared.csproj" />
    <ProjectReference Include="..\ABP.Infraestructure.Persistence\ABP.Infraestructure.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fido2.AspNet" Version="4.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.19" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.19" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
