# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated9.0 AS base
WORKDIR /home/site/wwwroot
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Source/Presentation/Functions/ABP.Functions/ABP.Functions.csproj", "Source/Presentation/Functions/ABP.Functions/"]
COPY ["Source/Core/ABP.Core.Application/ABP.Core.Application.csproj", "Source/Core/ABP.Core.Application/"]
COPY ["Source/Core/ABP.Core.Domain/ABP.Core.Domain.csproj", "Source/Core/ABP.Core.Domain/"]
COPY ["Source/Infraestructure/ABP.Infraestructure.Persistence/ABP.Infraestructure.Persistence.csproj", "Source/Infraestructure/ABP.Infraestructure.Persistence/"]
COPY ["Source/Infraestructure/ABP.Infraestructure.Shared/ABP.Infraestructure.Shared.csproj", "Source/Infraestructure/ABP.Infraestructure.Shared/"]
RUN dotnet restore "./Source/Presentation/Functions/ABP.Functions/ABP.Functions.csproj"
COPY . .
WORKDIR "/src/Source/Presentation/Functions/ABP.Functions"
RUN dotnet build "./ABP.Functions.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./ABP.Functions.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /home/site/wwwroot
COPY --from=publish /app/publish .
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true
